**Choco Crunch Analytics — Data Exploration and Cleaning**

**Load the Raw Dataset**

The raw dataset collected from the Open Food Facts API is loaded from `chococrunch_raw.csv` into a Pandas DataFrame.

The display option is configured to show all columns when inspecting the dataset. The first few records are displayed to get an initial view of the data.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns
df = pd.read_csv("chococrunch_raw.csv")

df.head()

C:\Users\Meiappan\AppData\Local\Temp\ipykernel_8384\1062746967.py:3: DtypeWarning: Columns (0: nutriments.chloride_unit, 1: nutriments.bicarbonate_unit, 2: nutriments.fluoride_unit, 3: nutriments.ph_modifier, 4: nutriments.ph_unit, 5: nutriments.alpha-linolenic-acid_unit, 6: nutriments.arachidic-acid_unit, 7: nutriments.arachidonic-acid_unit, 8: nutriments.behenic-acid_unit, 9: nutriments.bicarbonate_label, 10: nutriments.biotin_unit, 11: nutriments.butyric-acid_unit, 12: nutriments.chloride_label, 13: nutriments.fluoride_label, 14: nutriments.magnesium_label, 15: nutriments.nitrate_label, 16: nutriments.nitrate_modifier, 17: nutriments.nitrate_unit, 18: nutriments.potassium_label, 19: nutriments.silica_label, 20: nutriments.silica_unit, 21: nutriments.sulphate_label, 22: nutriments.sulphate_unit, 23: nutriments.vitamin-b1_label, 24: nutriments.vitamin-b2_label, 25: nutriments.vitamin-b9_label, 26: nutriments.vitamin-pp_label, 27: nutriments.cocoa_label, 28: nutriments.vitamin-b6_label, 29: nutriments.vitamin-e_label, 30: nutriments.phosphorus_label, 31: nutriments.monounsaturated-fat_label, 32: nutriments.oleic-acid_unit, 33: nutriments.polyunsaturated-fat_label, 34: nutriments.sugars_modifier, 35: nutriments.fruits-vegetables-nuts_label, 36: nutriments.iodine_unit, 37: nutriments.calcium_modifier, 38: nutriments.iron_label, 39: nutriments.iron_modifier, 40: nutriments.vitamin-a_label, 41: nutriments.vitamin-a_modifier, 42: nutriments.vitamin-c_label, 43: nutriments.vitamin-c_modifier, 44: nutriments.fr-residu-sec-a-105-c_label, 45: nutriments.fr-residu-sec-a-105-c_unit, 46: nutriments.cholesterol_label, 47: nutriments.trans-fat_label, 48: nutriments.nutrition-score_unit, 49: nutriments.iodine_label, 50: nutriments.carbohydrates_modifier, 51: nutriments.omega-3-fat_label, 52: nutriments.omega-3-fat_unit, 53: nutriments.omega-6-fat_label, 54: nutriments.omega-6-fat_unit, 55: nutriments.omega-9-fat_label, 56: nutriments.omega-9-fat_unit, 57: nutriments.proteins_modifier, 58: nutriments.alcohol_modifier, 59: nutriments.copper_label, 60: nutriments.zinc_label, 61: nutriments.alpha-linolenic-acid_modifier, 62: nutriments.cholesterol_modifier, 63: nutriments.trans-fat_modifier, 64: nutriments.alcohol_prepared_unit, 65: nutriments.carbon-footprint_prepared_unit, 66: nutriments.fruits-vegetables-nuts_prepared_unit, 67: nutriments.sterco-di-mucca_prepared_unit, 68: nutriments.lactose_label, 69: nutriments.lactose_unit, 70: nutriments.bicarbonate_prepared_unit, 71: nutriments.calcium_prepared_unit, 72: nutriments.chloride_prepared_unit, 73: nutriments.en-strontium_prepared_unit, 74: nutriments.en-sulfate_prepared_unit, 75: nutriments.fluoride_prepared_unit, 76: nutriments.fr-strontium_prepared_unit, 77: nutriments.fr-sulfate_prepared_unit, 78: nutriments.magnesium_prepared_unit, 79: nutriments.nitrate_prepared_unit, 80: nutriments.ph_prepared_unit, 81: nutriments.potassium_prepared_unit, 82: nutriments.alpha-linolenic-acid_label, 83: nutriments.linoleic-acid_label, 84: nutriments.linoleic-acid_unit, 85: nutriments.maltodextrins_unit, 86: nutriments.ph_label, 87: nutriments.pantothenic-acid_label, 88: nutriments.fluoride_modifier, 89: nutriments.maltodextrins_label, 90: nutriments.fructose_label, 91: nutriments.fructose_unit, 92: nutriments.fiber_prepared_modifier, 93: nutriments.vitamin-c_prepared_unit, 94: nutriments.vitamin-d_prepared_unit, 95: nutriments.oleic-acid_label, 96: nutriments.polyols_label, 97: nutriments.iron_prepared_unit, 98: nutriments.phosphorus_prepared_unit, 99: nutriments.carbon-footprint_unit, 100: nutriments.beta-glucan_label, 101: nutriments.beta-glucan_unit, 102: nutriments.vitamin-b1_prepared_unit, 103: nutriments.zinc_prepared_unit, 104: nutriments.fruits-vegetables-nuts-dried_unit, 105: nutriments.extrait-sec-a-180-c_prepared_unit, 106: nutriments.fr-extrait-sec-a-180-c_prepared_unit, 107: nutriments.fr-nitrates_prepared_unit, 108: nutriments.fr-sulfates_prepared_unit, 109: nutriments.nitrates_prepared_unit, 110: nutriments.silica_prepared_unit, 111: nutriments.sulfates_prepared_unit, 112: nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_unit, 113: nutriments.cocoa_prepared_unit, 114: nutriments.0_unit, 115: nutriments.pantothenic-acid_prepared_unit, 116: nutriments.vitamin-b2_prepared_unit, 117: nutriments.vitamin-b6_prepared_unit, 118: nutriments.vitamin-b9_prepared_unit, 119: nutriments.vitamin-pp_prepared_unit, 120: nutriments.dry-residue_label, 121: nutriments.dry-residue_unit, 122: nutriments.en-0_unit, 123: nutriments.beta-carotene_label, 124: nutriments.beta-carotene_unit, 125: nutriments.starch_label, 126: nutriments.energy-kcal_modifier, 127: nutriments.en-fibres-du-son-de-ble_label, 128: nutriments.en-fibres-du-son-de-ble_unit, 129: nutriments.polyols_prepared_unit, 130: nutriments.gamma-linolenic-acid_unit, 131: nutriments.energy-g_unit, 132: nutriments.vitamin-e_modifier, 133: nutriments.serum-proteins_unit, 134: nutriments.molybdenum_unit, 135: nutriments.glucides assimilables_unit, 136: nutriments.fr-extrait-sec-a-180-c_label, 137: nutriments.fr-extrait-sec-a-180-c_unit, 138: nutriments.fr-nitrates_label, 139: nutriments.fr-nitrates_unit, 140: nutriments.fr-sulfates_label, 141: nutriments.fr-sulfates_unit, 142: nutriments.caffeine_prepared_unit, 143: nutriments.fr-residu-a-sec_label, 144: nutriments.fr-residu-a-sec_unit, 145: nutriments.starch_modifier, 146: nutriments.vitamin-b1_modifier, 147: nutriments.selenium_label, 148: nutriments.fr-0_unit, 149: nutriments.biotin_label, 150: nutriments.vitamin-a_prepared_unit, 151: nutriments.vitamin-e_prepared_unit, 152: nutriments.potassium_modifier, 153: nutriments.salt_modifier, 154: nutriments.sodium_modifier, 155: nutriments.fr-strontium_label, 156: nutriments.fr-strontium_unit, 157: nutriments.lactose_modifier, 158: nutriments.fr-residu-sec_label, 159: nutriments.fr-residu-sec_unit, 160: nutriments.fr-residu-sec-a-180-c_label, 161: nutriments.fr-residu-sec-a-180-c_unit, 162: nutriments.nitrite_label, 163: nutriments.nitrite_unit, 164: nutriments.biotin_prepared_unit, 165: nutriments.fat_prepared_modifier, 166: nutriments.proteins_prepared_modifier, 167: nutriments.saturated-fat_prepared_modifier, 168: nutriments.sugars_prepared_modifier, 169: nutriments.vitamin-b12_prepared_unit, 170: nutriments.new_1_prepared_unit, 171: nutriments.fr-nitrate_label, 172: nutriments.fr-nitrate_unit, 173: nutriments.chromium_label, 174: nutriments.chromium_unit, 175: nutriments.manganese_label, 176: nutriments.cerotic-acid_unit, 177: nutriments.carbohydrates_prepared_modifier, 178: nutriments.fr-sulfate_label, 179: nutriments.fr-sulfate_unit, 180: nutriments.fr-riboflavine-b2_label, 181: nutriments.fr-riboflavine-b2_unit, 182: nutriments.elaidic-acid_unit, 183: nutriments.pl-0_unit, 184: nutriments.taurine_unit, 185: nutriments.fr-بقايا-جافة_label, 186: nutriments.fr-بقايا-جافة_unit, 187: nutriments.fr-بوتاسيوم_label, 188: nutriments.fr-بوتاسيوم_unit, 189: nutriments.fr-بيكربونات_label, 190: nutriments.fr-بيكربونات_unit, 191: nutriments.fr-سولفات_label, 192: nutriments.fr-سولفات_unit, 193: nutriments.fr-كلسيوم_label, 194: nutriments.fr-كلسيوم_unit, 195: nutriments.fr-كلورور_label, 196: nutriments.fr-كلورور_unit, 197: nutriments.fr-مانزيوم_label, 198: nutriments.fr-مانزيوم_unit, 199: nutriments.fr-نيترات_label, 200: nutriments.fr-نيترات_unit, 201: nutriments.lignoceric-acid_unit, 202: nutriments.maltose_unit, 203: nutriments.fr-residu-sec-a-180-c_prepared_unit, 204: nutriments.fruits-vegetables-nuts-dried_label, 205: nutriments.phylloquinone_unit, 206: nutriments.added-sugars_label, 207: nutriments.nutrition-score-fr_unit, 208: nutriments.es-vitamina-e_label, 209: nutriments.es-vitamina-e_unit, 210: nutriments.salt_prepared_modifier, 211: nutriments.sodium_prepared_modifier, 212: nutriments.poisson_label, 213: nutriments.poisson_unit, 214: nutriments.monounsaturated-fat_modifier, 215: nutriments.de-mate_label, 216: nutriments.de-mate_unit, 217: nutriments.fr-nitrite_label, 218: nutriments.fr-nitrite_unit, 219: nutriments.es-betaglucanos_label, 220: nutriments.es-betaglucanos_unit, 221: nutriments.energy-from-fat_unit, 222: nutriments.monounsaturated-fat_prepared_unit, 223: nutriments.polyunsaturated-fat_prepared_unit, 224: nutriments.starch_prepared_unit, 225: nutriments.docosahexaenoic-acid_label, 226: nutriments.docosahexaenoic-acid_unit, 227: nutriments.eicosapentaenoic-acid_label, 228: nutriments.eicosapentaenoic-acid_unit, 229: nutriments.en-vitamine-b12-cobalamine_label, 230: nutriments.en-vitamine-b12-cobalamine_unit, 231: nutriments.cholesterol_prepared_unit, 232: nutriments.iodine_prepared_unit, 233: nutriments.selenium_prepared_unit, 234: nutriments.ro-tds_label, 235: nutriments.ro-tds_unit, 236: nutriments.en-omega-3-ala_label, 237: nutriments.en-omega-3-ala_unit, 238: nutriments.soluble-fiber_label, 239: nutriments.soluble-fiber_unit, 240: nutriments.choline_label, 241: nutriments.caffeine_label, 242: nutriments.fr-chrlorures_label, 243: nutriments.fr-chrlorures_unit, 244: nutriments.pt-vitamina-b1_label, 245: nutriments.pt-vitamina-b1_unit, 246: nutriments.en-mono-unsaturates_label, 247: nutriments.en-mono-unsaturates_unit, 248: nutriments.en-polyunsaturates_label, 249: nutriments.en-polyunsaturates_unit, 250: nutriments.added-sugars_prepared_unit, 251: nutriments.trans-fat_prepared_unit, 252: nutriments.folates_label, 253: nutriments.folates_unit, 254: nutriments.molybdenum_label, 255: nutriments.fr-clcium_label, 256: nutriments.fr-clcium_unit, 257: nutriments.polyunsaturated-fat_modifier, 258: nutriments.phosphorous_label, 259: nutriments.phosphorous_unit, 260: nutriments.palmitic-acid_unit, 261: nutriments.fr-resdu-sec-a-180-c_label, 262: nutriments.fr-resdu-sec-a-180-c_unit, 263: nutriments.es-acide-alpha-linolenique-omega-3_label, 264: nutriments.es-acide-alpha-linolenique-omega-3_unit, 265: nutriments.fr-vitamine-b9-m-acide-folique_label, 266: nutriments.fr-vitamine-b9-m-acide-folique_unit, 267: nutriments.fr-vitamine-pp-b3-niacine_label, 268: nutriments.fr-vitamine-pp-b3-niacine_unit, 269: nutriments.fruits-vegetables-nuts-estimate-from-ingredients_label, 270: nutriments.fruits-vegetables-nuts-estimate-from-ingredients_unit, 271: nutriments.fr-hydrogencarbonat_label, 272: nutriments.fr-hydrogencarbonat_unit, 273: nutriments.fr-sulfat_label, 274: nutriments.fr-sulfat_unit, 275: nutriments.fr-chlorid_label, 276: nutriments.fr-chlorid_unit, 277: nutriments.alcohol_prepared_modifier, 278: nutriments.myristic-acid_unit, 279: nutriments.salt-equivalent_unit, 280: nutriments.de-hydrogencarbonat_label, 281: nutriments.de-hydrogencarbonat_unit, 282: nutriments.de-nitrat_label, 283: nutriments.de-nitrat_modifier, 284: nutriments.de-nitrat_unit, 285: nutriments.insoluble-fiber_unit, 286: nutriments.fr-nitrates_modifier, 287: nutriments.collagen-meat-protein-ratio_unit, 288: nutriments.energy-kcal_prepared_modifier, 289: nutriments.energy-kj_prepared_modifier, 290: nutriments.energy_prepared_modifier, 291: nutriments.erythritol_label, 292: nutriments.erythritol_unit, 293: nutriments.chlorures_label, 294: nutriments.chlorures_unit, 295: nutriments.hydrogenocarbonates_label, 296: nutriments.hydrogenocarbonates_unit, 297: nutriments.nitrates_label, 298: nutriments.nitrates_modifier, 299: nutriments.nitrates_unit, 300: nutriments.residu-a-sec-a-180-c_label, 301: nutriments.residu-a-sec-a-180-c_unit, 302: nutriments.sodium_label, 303: nutriments.sulfates_label, 304: nutriments.sulfates_unit, 305: nutriments.water_label, 306: nutriments.water_unit, 307: nutriments.sucrose_unit, 308: nutriments.omega-3-fat_prepared_unit, 309: nutriments.fr-acides-gras-insatures_label, 310: nutriments.fr-acides-gras-insatures_unit, 311: nutriments.nervonic-acid_unit, 312: nutriments.gondoic-acid_unit, 313: nutriments.en-total-sugars_label, 314: nutriments.en-total-sugars_unit, 315: nutriments.carbon-footprint-from-meat-or-fish_unit, 316: nutriments.de-wasser_label, 317: nutriments.de-wasser_modifier, 318: nutriments.de-wasser_unit, 319: nutriments.docosahexaenoic-acid_prepared_unit, 320: nutriments.eicosapentaenoic-acid_prepared_unit, 321: nutriments.en-b2_label, 322: nutriments.en-b2_unit, 323: nutriments.en-eisen_label, 324: nutriments.en-eisen_unit, 325: nutriments.en-vatimin-a_label, 326: nutriments.en-vatimin-a_unit, 327: nutriments.de-sulfat_label, 328: nutriments.de-sulfat_unit, 329: nutriments.capric-acid_unit, 330: nutriments.caproic-acid_unit, 331: nutriments.caprylic-acid_unit, 332: nutriments.en-minerals_label, 333: nutriments.en-minerals_unit, 334: nutriments.en-omega-3_label, 335: nutriments.en-omega-3_unit, 336: nutriments.riboflavine-b2_label, 337: nutriments.riboflavine-b2_unit, 338: nutriments.energy-kj_modifier, 339: nutriments.fr-dry-residue-at-180-c_label, 340: nutriments.fr-dry-residue-at-180-c_unit, 341: nutriments.en-monounsaturated-fat5_label, 342: nutriments.en-monounsaturated-fat5_unit, 343: nutriments.en-vitamin-d2_label, 344: nutriments.en-vitamin-d2_unit, 345: nutriments.fr-poisson_label, 346: nutriments.fr-poisson_unit, 347: nutriments.dont-acides-gras-mono-insatures_label, 348: nutriments.dont-acides-gras-mono-insatures_unit, 349: nutriments.dont-acides-gras-poly-insature_label, 350: nutriments.dont-acides-gras-poly-insature_unit, 351: nutriments.de-chlorid_label, 352: nutriments.de-chlorid_unit, 353: nutriments.de-flourid_label, 354: nutriments.de-flourid_unit, 355: nutriments.fr-fibres-alimentaired_label, 356: nutriments.fr-fibres-alimentaired_unit, 357: nutriments.de-sulfate_label, 358: nutriments.de-sulfate_unit, 359: nutriments.fr-nitrites_label, 360: nutriments.fr-nitrites_unit, 361: nutriments.beta-glucane-d-avoine_label, 362: nutriments.beta-glucane-d-avoine_modifier, 363: nutriments.beta-glucane-d-avoine_unit) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("chococrunch_raw.csv")

,brands,code,product_name,nutriments.carbohydrates,nutriments.carbohydrates_100g,nutriments.carbohydrates_serving,nutriments.carbohydrates_unit,nutriments.carbohydrates_value,nutriments.energy,nutriments.energy-kcal,nutriments.energy-kcal_100g,nutriments.energy-kcal_serving,nutriments.energy-kcal_unit,nutriments.energy-kcal_value,nutriments.energy-kcal_value_computed,nutriments.energy-kj,nutriments.energy-kj_100g,nutriments.energy-kj_serving,nutriments.energy-kj_unit,nutriments.energy-kj_value,nutriments.energy-kj_value_computed,nutriments.energy_100g,nutriments.energy_serving,nutriments.energy_unit,nutriments.energy_value,nutriments.fat,nutriments.fat_100g,nutriments.fat_serving,nutriments.fat_unit,nutriments.fat_value,nutriments.fiber,nutriments.fiber_100g,nutriments.fiber_serving,nutriments.fiber_unit,nutriments.fiber_value,nutriments.fruits-vegetables-legumes-estimate-from-ingredients_100g,nutriments.fruits-vegetables-legumes-estimate-from-ingredients_serving,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_serving,nutriments.nutrition-score-fr,nutriments.nutrition-score-fr_100g,nutriments.proteins,nutriments.proteins_100g,nutriments.proteins_serving,nutriments.proteins_unit,nutriments.proteins_value,nutriments.salt,nutriments.salt_100g,nutriments.salt_serving,nutriments.salt_unit,nutriments.salt_value,nutriments.saturated-fat,nutriments.saturated-fat_100g,nutriments.saturated-fat_serving,nutriments.saturated-fat_unit,nutriments.saturated-fat_value,nutriments.sodium,nutriments.sodium_100g,nutriments.sodium_serving,nutriments.sodium_unit,nutriments.sodium_value,nutriments.sugars,nutriments.sugars_100g,nutriments.sugars_serving,nutriments.sugars_unit,nutriments.sugars_value,nutriments.calcium,nutriments.calcium_100g,nutriments.calcium_label,nutriments.calcium_serving,nutriments.calcium_unit,nutriments.calcium_value,nutriments.fat_label,nutriments.nova-group,nutriments.nova-group_100g,nutriments.nova-group_serving,nutriments.chloride,nutriments.chloride_100g,nutriments.chloride_unit,nutriments.chloride_value,nutriments.magnesium,nutriments.magnesium_100g,nutriments.magnesium_unit,nutriments.magnesium_value,nutriments.potassium,nutriments.potassium_100g,nutriments.potassium_unit,nutriments.potassium_value,nutriments.alcohol,nutriments.alcohol_100g,nutriments.alcohol_serving,nutriments.alcohol_unit,nutriments.alcohol_value,nutriments.bicarbonate,nutriments.bicarbonate_100g,nutriments.bicarbonate_serving,nutriments.bicarbonate_unit,nutriments.bicarbonate_value,nutriments.fluoride,nutriments.fluoride_100g,nutriments.fluoride_serving,nutriments.fluoride_unit,nutriments.fluoride_value,nutriments.iron,nutriments.iron_100g,nutriments.iron_serving,nutriments.iron_unit,nutriments.iron_value,nutriments.magnesium_serving,nutriments.ph,nutriments.ph_100g,nutriments.ph_modifier,nutriments.ph_serving,nutriments.ph_unit,nutriments.ph_value,nutriments.potassium_serving,nutriments.fiber_modifier,nutriments.alpha-linolenic-acid,nutriments.alpha-linolenic-acid_100g,nutriments.alpha-linolenic-acid_serving,nutriments.alpha-linolenic-acid_unit,nutriments.alpha-linolenic-acid_value,nutriments.arachidic-acid,nutriments.arachidic-acid_100g,nutriments.arachidic-acid_serving,nutriments.arachidic-acid_unit,nutriments.arachidic-acid_value,nutriments.arachidonic-acid,nutriments.arachidonic-acid_100g,nutriments.arachidonic-acid_serving,nutriments.arachidonic-acid_unit,nutriments.arachidonic-acid_value,nutriments.behenic-acid,nutriments.behenic-acid_100g,nutriments.behenic-acid_serving,nutriments.behenic-acid_unit,nutriments.behenic-acid_value,nutriments.bicarbonate_label,nutriments.biotin,nutriments.biotin_100g,nutriments.biotin_serving,nutriments.biotin_unit,nutriments.biotin_value,nutriments.butyric-acid,nutriments.butyric-acid_100g,nutriments.butyric-acid_serving,nutriments.butyric-acid_unit,nutriments.butyric-acid_value,nutriments.carbon-footprint-from-known-ingredients_product,nutriments.chloride_label,nutriments.chloride_serving,nutriments.fluoride_label,nutriments.magnesium_label,nutriments.nitrate,nutriments.nitrate_100g,nutriments.nitrate_label,nutriments.nitrate_modifier,nutriments.nitrate_serving,nutriments.nitrate_unit,nutriments.nitrate_value,nutriments.potassium_label,nutriments.silica,nutriments.silica_100g,nutriments.silica_label,nutriments.silica_serving,nutriments.silica_unit,nutriments.silica_value,nutriments.sulphate,nutriments.sulphate_100g,nutriments.sulphate_label,nutriments.sulphate_serving,nutriments.sulphate_unit,nutriments.sulphate_value,nutriments.fat_modifier,nutriments.saturated-fat_modifier,nutriments.vitamin-b1,nutriments.vitamin-b12,nutriments.vitamin-b12_100g,nutriments.vitamin-b12_label,nutriments.vitamin-b12_serving,nutriments.vitamin-b12_unit,nutriments.vitamin-b12_value,nutriments.vitamin-b1_100g,nutriments.vitamin-b1_label,nutriments.vitamin-b1_serving,nutriments.vitamin-b1_unit,nutriments.vitamin-b1_value,nutriments.vitamin-b2,nutriments.vitamin-b2_100g,nutriments.vitamin-b2_label,nutriments.vitamin-b2_serving,nutriments.vitamin-b2_unit,nutriments.vitamin-b2_value,nutriments.vitamin-b9,nutriments.vitamin-b9_100g,nutriments.vitamin-b9_label,nutriments.vitamin-b9_serving,nutriments.vitamin-b9_unit,nutriments.vitamin-b9_value,nutriments.vitamin-pp,nutriments.vitamin-pp_100g,nutriments.vitamin-pp_label,nutriments.vitamin-pp_serving,nutriments.vitamin-pp_unit,nutriments.vitamin-pp_value,nutriments.carbohydrates_prepared_unit,nutriments.carbon-footprint-from-known-ingredients_100g,nutriments.carbon-footprint-from-known-ingredients_serving,nutriments.energy-kcal_prepared_unit,nutriments.energy-kj_prepared_unit,nutriments.energy_prepared_unit,nutriments.fat_prepared_unit,nutriments.fiber_prepared_unit,nutriments.proteins_prepared_unit,nutriments.salt_prepared_unit,nutriments.saturated-fat_prepared_unit,nutriments.sodium_prepared_unit,nutriments.sugars_prepared_unit,nutriments.choline,nutriments.choline_100g,nutriments.choline_serving,nutriments.choline_unit,nutriments.choline_value,nutriments.cocoa,nutriments.cocoa_100g,nutriments.cocoa_label,nutriments.cocoa_serving,nutriments.cocoa_unit,nutriments.cocoa_value,nutriments.starch,nutriments.starch_100g,nutriments.starch_serving,nutriments.starch_unit,nutriments.starch_value,nutriments.fruits-vegetables-nuts-estimate,nutriments.fruits-vegetables-nuts-estimate_100g,nutriments.fruits-vegetables-nuts-estimate_label,nutriments.fruits-vegetables-nuts-estimate_serving,nutriments.fruits-vegetables-nuts-estimate_unit,nutriments.fruits-vegetables-nuts-estimate_value,nutriments.fruits-vegetables-nuts,nutriments.fruits-vegetables-nuts_100g,nutriments.fruits-vegetables-nuts_serving,nutriments.fruits-vegetables-nuts_unit,nutriments.fruits-vegetables-nuts_value,nutriments.vitamin-b6,nutriments.vitamin-b6_100g,nutriments.vitamin-b6_label,nutriments.vitamin-b6_serving,nutriments.vitamin-b6_unit,nutriments.vitamin-b6_value,nutriments.vitamin-e,nutriments.vitamin-e_100g,nutriments.vitamin-e_label,nutriments.vitamin-e_serving,nutriments.vitamin-e_unit,nutriments.vitamin-e_value,nutriments.phosphorus,nutriments.phosphorus_100g,nutriments.phosphorus_label,nutriments.phosphorus_unit,nutriments.phosphorus_value,nutriments.monounsaturated-fat,nutriments.monounsaturated-fat_100g,nutriments.monounsaturated-fat_label,nutriments.monounsaturated-fat_serving,nutriments.monounsaturated-fat_unit,nutriments.monounsaturated-fat_value,nutriments.oleic-acid,nutriments.oleic-acid_100g,nutriments.oleic-acid_serving,nutriments.oleic-acid_unit,nutriments.oleic-acid_value,nutriments.polyunsaturated-fat,nutriments.polyunsaturated-fat_100g,nutriments.polyunsaturated-fat_label,nutriments.polyunsaturated-fat_serving,nutriments.polyunsaturated-fat_unit,nutriments.polyunsaturated-fat_value,nutriments.sugars_modifier,nutriments.vitamin-d,nutriments.vitamin-d_100g,nutriments.vitamin-d_label,nutriments.vitamin-d_serving,nutriments.vitamin-d_unit,nutriments.vitamin-d_value,nutriments.added-sugars,nutriments.added-sugars_100g,nutriments.added-sugars_serving,nutriments.added-sugars_unit,nutriments.added-sugars_value,nutriments.caffeine,nutriments.caffeine_100g,nutriments.caffeine_serving,nutriments.caffeine_unit,nutriments.caffeine_value,nutriments.copper,nutriments.copper_100g,nutriments.copper_serving,nutriments.copper_unit,nutriments.copper_value,nutriments.manganese,nutriments.manganese_100g,nutriments.manganese_serving,nutriments.manganese_unit,nutriments.manganese_value,nutriments.phosphorus_serving,nutriments.selenium,nutriments.selenium_100g,nutriments.selenium_serving,nutriments.selenium_unit,nutriments.selenium_value,nutriments.vitamin-a,nutriments.vitamin-a_100g,nutriments.vitamin-a_serving,nutriments.vitamin-a_unit,nutriments.vitamin-a_value,nutriments.vitamin-c,nutriments.vitamin-c_100g,nutriments.vitamin-c_serving,nutriments.vitamin-c_unit,nutriments.vitamin-c_value,nutriments.vitamin-k,nutriments.vitamin-k_100g,nutriments.vitamin-k_serving,nutriments.vitamin-k_unit,nutriments.vitamin-k_value,nutriments.zinc,nutriments.zinc_100g,nutriments.zinc_serving,nutriments.zinc_unit,nutriments.zinc_value,nutriments.fruits-vegetables-nuts_label,nutriments.iodine,nutriments.iodine_100g,nutriments.iodine_unit,nutriments.iodine_value,nutriments.pantothenic-acid,nutriments.pantothenic-acid_100g,nutriments.pantothenic-acid_serving,nutriments.pantothenic-acid_unit,nutriments.pantothenic-acid_value,nutriments.calcium_modifier,nutriments.iron_label,nutriments.iron_modifier,nutriments.vitamin-a_label,nutriments.vitamin-a_modifier,nutriments.vitamin-c_label,nutriments.vitamin-c_modifier,nutriments.cholesterol,nutriments.cholesterol_100g,nutriments.cholesterol_serving,nutriments.cholesterol_unit,nutriments.cholesterol_value,nutriments.fr-residu-sec-a-105-c,nutriments.fr-residu-sec-a-105-c_100g,nutriments.fr-residu-sec-a-105-c_label,nutriments.fr-residu-sec-a-105-c_serving,nutriments.fr-residu-sec-a-105-c_unit,nutriments.fr-residu-sec-a-105-c_value,nutriments.trans-fat,nutriments.trans-fat_100g,nutriments.trans-fat_serving,nutriments.trans-fat_unit,nutriments.trans-fat_value,nutriments.cholesterol_label,nutriments.trans-fat_label,nutriments.nutrition-score_unit,nutriments.nutrition-score_value,nutriments.iodine_label,nutriments.iodine_serving,nutriments.carbohydrates_modifier,nutriments.omega-3-fat,nutriments.omega-3-fat_100g,nutriments.omega-3-fat_label,nutriments.omega-3-fat_unit,nutriments.omega-3-fat_value,nutriments.omega-6-fat,nutriments.omega-6-fat_100g,nutriments.omega-6-fat_label,nutriments.omega-6-fat_unit,nutriments.omega-6-fat_value,nutriments.omega-9-fat,nutriments.omega-9-fat_100g,nutriments.omega-9-fat_label,nutriments.omega-9-fat_unit,nutriments.omega-9-fat_value,nutriments.proteins_modifier,nutriments.alcohol_modifier,nutriments.omega-6-fat_serving,nutriments.copper_label,nutriments.zinc_label,nutriments.alpha-linolenic-acid_modifier,nutriments.cholesterol_modifier,nutriments.trans-fat_modifier,nutriments.alcohol_prepared_unit,nutriments.carbon-footprint_prepared_unit,nutriments.fruits-vegetables-nuts_prepared_unit,nutriments.sterco-di-mucca_prepared_unit,nutriments.lactose,nutriments.lactose_100g,nutriments.lactose_label,nutriments.lactose_serving,nutriments.lactose_unit,nutriments.lactose_value,nutriments.carbohydrates_prepared,nutriments.carbohydrates_prepared_100g,nutriments.carbohydrates_prepared_serving,nutriments.carbohydrates_prepared_value,nutriments.energy-kcal_prepared,nutriments.energy-kcal_prepared_100g,nutriments.energy-kcal_prepared_serving,nutriments.energy-kcal_prepared_value,nutriments.energy-kj_prepared,nutriments.energy-kj_prepared_100g,nutriments.energy-kj_prepared_serving,nutriments.energy-kj_prepared_value,nutriments.energy_prepared,nutriments.energy_prepared_100g,nutriments.energy_prepared_serving,nutriments.energy_prepared_value,nutriments.fat_prepared,nutriments.fat_prepared_100g,nutriments.fat_prepared_serving,nutriments.fat_prepared_value,nutriments.fiber_prepared,nutriments.fiber_prepared_100g,nutriments.fiber_prepared_serving,nutriments.fiber_prepared_value,nutriments.proteins_prepared,nutriments.proteins_prepared_100g,nutriments.proteins_prepared_serving,nutriments.proteins_prepared_value,nutriments.salt_prepared,nutriments.salt_prepared_100g,nutriments.salt_prepared_serving,nutriments.salt_prepared_value,nutriments.saturated-fat_prepared,nutriments.saturated-fat_prepared_100g,nutriments.saturated-fat_prepared_serving,nutriments.saturated-fat_prepared_value,nutriments.sodium_prepared,nutriments.sodium_prepared_100g,nutriments.sodium_prepared_serving,nutriments.sodium_prepared_value,nutriments.sugars_prepared,nutriments.sugars_prepared_100g,nutriments.sugars_prepared_serving,nutriments.sugars_prepared_value,nutriments.bicarbonate_prepared_unit,nutriments.calcium_prepared_unit,nutriments.chloride_prepared_unit,nutriments.en-strontium_prepared_unit,nutriments.en-sulfate_prepared_unit,nutriments.fluoride_prepared_unit,nutriments.fr-strontium_prepared,nutriments.fr-strontium_prepared_serving,nutriments.fr-strontium_prepared_unit,nutriments.fr-strontium_prepared_value,nutriments.fr-sulfate_prepared,nutriments.fr-sulfate_prepared_serving,nutriments.fr-sulfate_prepared_unit,nutriments.fr-sulfate_prepared_value,nutriments.magnesium_prepared_unit,nutriments.nitrate_prepared_unit,nutriments.ph_prepared_unit,nutriments.potassium_prepared_unit,nutriments.alpha-linolenic-acid_label,nutriments.linoleic-acid,nutriments.linoleic-acid_100g,nutriments.linoleic-acid_label,nutriments.linoleic-acid_unit,nutriments.linoleic-acid_value,nutriments.maltodextrins,nutriments.maltodextrins_100g,nutriments.maltodextrins_unit,nutriments.maltodextrins_value,nutriments.ph_label,nutriments.pantothenic-acid_label,nutriments.omega-3-fat_serving,nutriments.fluoride_modifier,nutriments.magnesium_prepared,nutriments.magnesium_prepared_100g,nutriments.magnesium_prepared_serving,nutriments.magnesium_prepared_value,nutriments.maltodextrins_label,nutriments.fructose,nutriments.fructose_100g,nutriments.fructose_label,nutriments.fructose_serving,nutriments.fructose_unit,nutriments.fructose_value,nutriments.calcium_prepared,nutriments.calcium_prepared_100g,nutriments.calcium_prepared_value,nutriments.fiber_prepared_modifier,nutriments.vitamin-c_prepared,nutriments.vitamin-c_prepared_100g,nutriments.vitamin-c_prepared_unit,nutriments.vitamin-c_prepared_value,nutriments.vitamin-d_prepared,nutriments.vitamin-d_prepared_100g,nutriments.vitamin-d_prepared_unit,nutriments.vitamin-d_prepared_value,nutriments.acides-gras-mono-insatures_100g,nutriments.acides-gras-mono-insatures_serving,nutriments.acides-gras-polyinsatures_100g,nutriments.acides-gras-polyinsatures_serving,nutriments.oleic-acid_label,nutriments.polyols,nutriments.polyols_100g,nutriments.polyols_label,nutriments.polyols_serving,nutriments.polyols_unit,nutriments.polyols_value,nutriments.iron_prepared_unit,nutriments.phosphorus_prepared_unit,nutriments.carbon-footprint,nutriments.carbon-footprint_100g,nutriments.carbon-footprint_serving,nutriments.carbon-footprint_unit,nutriments.carbon-footprint_value,nutriments.beta-glucan,nutriments.beta-glucan_100g,nutriments.beta-glucan_label,nutriments.beta-glucan_serving,nutriments.beta-glucan_unit,nutriments.beta-glucan_value,nutriments.calcium_prepared_serving,nutriments.iron_prepared,nutriments.iron_prepared_100g,nutriments.iron_prepared_serving,nutriments.iron_prepared_value,nutriments.phosphorus_prepared,nutriments.phosphorus_prepared_100g,nutriments.phosphorus_prepared_serving,nutriments.phosphorus_prepared_value,nutriments.potassium_prepared,nutriments.potassium_prepared_100g,nutriments.potassium_prepared_serving,nutriments.potassium_prepared_value,nutriments.vitamin-b1_prepared,nutriments.vitamin-b1_prepared_100g,nutriments.vitamin-b1_prepared_serving,nutriments.vitamin-b1_prepared_unit,nutriments.vitamin-b1_prepared_value,nutriments.vitamin-c_prepared_serving,nutriments.vitamin-d_prepared_serving,nutriments.zinc_prepared,nutriments.zinc_prepared_100g,nutriments.zinc_prepared_serving,nutriments.zinc_prepared_unit,nutriments.zinc_prepared_value,nutriments.fruits-vegetables-nuts-dried,nutriments.fruits-vegetables-nuts-dried_100g,nutriments.fruits-vegetables-nuts-dried_serving,nutriments.fruits-vegetables-nuts-dried_unit,nutriments.fruits-vegetables-nuts-dried_value,nutriments.extrait-sec-a-180-c_prepared,nutriments.extrait-sec-a-180-c_prepared_100g,nutriments.extrait-sec-a-180-c_prepared_serving,nutriments.extrait-sec-a-180-c_prepared_unit,nutriments.extrait-sec-a-180-c_prepared_value,nutriments.fr-extrait-sec-a-180-c_prepared_unit,nutriments.fr-nitrates_prepared,nutriments.fr-nitrates_prepared_100g,nutriments.fr-nitrates_prepared_serving,nutriments.fr-nitrates_prepared_unit,nutriments.fr-nitrates_prepared_value,nutriments.fr-sulfates_prepared,nutriments.fr-sulfates_prepared_100g,nutriments.fr-sulfates_prepared_serving,nutriments.fr-sulfates_prepared_unit,nutriments.fr-sulfates_prepared_value,nutriments.nitrates_prepared,nutriments.nitrates_prepared_100g,nutriments.nitrates_prepared_serving,nutriments.nitrates_prepared_unit,nutriments.nitrates_prepared_value,nutriments.silica_prepared_unit,nutriments.sulfates_prepared,nutriments.sulfates_prepared_100g,nutriments.sulfates_prepared_serving,nutriments.sulfates_prepared_unit,nutriments.sulfates_prepared_value,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_100g,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_serving,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_unit,nutriments.cocoa_prepared_unit,nutriments.0,nutriments.0_100g,nutriments.0_label,nutriments.0_serving,nutriments.0_unit,nutriments.0_value,nutriments.pantothenic-acid_prepared_unit,nutriments.vitamin-b2_prepared_unit,nutriments.vitamin-b6_prepared_unit,nutriments.vitamin-b9_prepared_unit,nutriments.vitamin-pp_prepared_unit,nutriments.dry-residue,nutriments.dry-residue_100g,nutriments.dry-residue_label,nutriments.dry-residue_serving,nutriments.dry-residue_unit,nutriments.dry-residue_value,nutriments.omega-9-fat_serving,nutriments.en-0,nutriments.en-0_100g,nutriments.en-0_label,nutriments.en-0_unit,nutriments.en-0_value,nutriments.beta-carotene,nutriments.beta-carotene_100g,nutriments.beta-carotene_label,nutriments.beta-carotene_unit,nutriments.beta-carotene_value,nutriments.maltodextrins_serving,nutriments.carbon-footprint-from-meat-or-fish_100g,nutriments.carbon-footprint-from-meat-or-fish_product,nutriments.carbon-footprint-from-meat-or-fish_serving,nutriments.starch_label,nutriments.energy-kcal_modifier,nutriments.en-fibres-du-son-de-ble,nutriments.en-fibres-du-son-de-ble_100g,nutriments.en-fibres-du-son-de-ble_label,nutriments.en-fibres-du-son-de-ble_serving,nutriments.en-fibres-du-son-de-ble_unit,nutriments.en-fibres-du-son-de-ble_value,nutriments.polyols_prepared_unit,nutriments.gamma-linolenic-acid,nutriments.gamma-linolenic-acid_100g,nutriments.gamma-linolenic-acid_serving,nutriments.gamma-linolenic-acid_unit,nutriments.gamma-linolenic-acid_value,nutriments.energy-g,nutriments.energy-g_100g,nutriments.energy-g_serving,nutriments.energy-g_unit,nutriments.energy-g_value,nutriments.vitamin-e_modifier,nutriments.phosphore_100g,nutriments.phosphore_serving,nutriments.serum-proteins,nutriments.serum-proteins_100g,nutriments.serum-proteins_serving,nutriments.serum-proteins_unit,nutr

In [2]:
## Inspect the Dataset Columns

## The column names are examined to understand the variables available in the raw dataset and to identify the fields that will be used during the exploration and cleaning process.

df.columns

Index(['brands', 'code', 'product_name', 'nutriments.carbohydrates',
       'nutriments.carbohydrates_100g', 'nutriments.carbohydrates_serving',
       'nutriments.carbohydrates_unit', 'nutriments.carbohydrates_value',
       'nutriments.energy', 'nutriments.energy-kcal',
       ...
       'nutriments.pantothenic-acid_prepared_100g',
       'nutriments.vitamin-b9_prepared_100g',
       'nutriments.vitamin-pp_prepared_100g',
       'nutriments.beta-glucane-d-avoine',
       'nutriments.beta-glucane-d-avoine_100g',
       'nutriments.beta-glucane-d-avoine_label',
       'nutriments.beta-glucane-d-avoine_modifier',
       'nutriments.beta-glucane-d-avoine_serving',
       'nutriments.beta-glucane-d-avoine_unit',
       'nutriments.beta-glucane-d-avoine_value'],
      dtype='str', length=1405)

In [3]:
## Check Dataset Dimensions

## The shape of the DataFrame is checked to determine the number of rows and columns currently present in the dataset.

df.shape

(12097, 1405)

In [4]:
## Check for Duplicate Records

## Duplicate records are identified by checking the DataFrame for completely duplicated rows.

## The total number of duplicate records is calculated to determine whether duplicate entries need to be removed from the dataset.

df.duplicated().sum()

np.int64(47)

In [5]:
## Remove Duplicate Records

## The duplicate records identified in the previous step are removed from the DataFrame.

## The `inplace=True` parameter applies the change directly to `df` without creating a separate DataFrame.

df.drop_duplicates(inplace=True)

In [6]:
## Verify the Updated Dataset Dimensions

## After removing duplicate records, the shape of the DataFrame is checked again to verify the updated number of rows and columns.

df.shape

(12050, 1405)

In [7]:
## Inspect Data Types and Dataset Structure

## The `info()` method is used to inspect the overall structure of the DataFrame.

## This provides information about the number of entries, column names, non-null values, and data types of each column.

df.info()

<class 'pandas.DataFrame'>
Index: 12050 entries, 0 to 12096
Columns: 1405 entries, brands to nutriments.beta-glucane-d-avoine_value
dtypes: float64(975), int64(1), object(43), str(386)
memory usage: 130.4+ MB

In [8]:
## Generate Descriptive Statistics

## Descriptive statistics are generated for the numerical columns in the dataset.

## This provides an initial understanding of the distribution of numerical variables, including their count, mean, standard deviation, minimum, maximum, and quartile values.

df.describe()

,code,nutriments.carbohydrates,nutriments.carbohydrates_100g,nutriments.carbohydrates_serving,nutriments.carbohydrates_value,nutriments.energy,nutriments.energy-kcal,nutriments.energy-kcal_100g,nutriments.energy-kcal_serving,nutriments.energy-kcal_value,nutriments.energy-kcal_value_computed,nutriments.energy-kj,nutriments.energy-kj_100g,nutriments.energy-kj_serving,nutriments.energy-kj_value,nutriments.energy-kj_value_computed,nutriments.energy_100g,nutriments.energy_serving,nutriments.energy_value,nutriments.fat,nutriments.fat_100g,nutriments.fat_serving,nutriments.fat_value,nutriments.fiber,nutriments.fiber_100g,nutriments.fiber_serving,nutriments.fiber_value,nutriments.fruits-vegetables-legumes-estimate-from-ingredients_100g,nutriments.fruits-vegetables-legumes-estimate-from-ingredients_serving,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_serving,nutriments.nutrition-score-fr,nutriments.nutrition-score-fr_100g,nutriments.proteins,nutriments.proteins_100g,nutriments.proteins_serving,nutriments.proteins_value,nutriments.salt,nutriments.salt_100g,nutriments.salt_serving,nutriments.salt_value,nutriments.saturated-fat,nutriments.saturated-fat_100g,nutriments.saturated-fat_serving,nutriments.saturated-fat_value,nutriments.sodium,nutriments.sodium_100g,nutriments.sodium_serving,nutriments.sodium_value,nutriments.sugars,nutriments.sugars_100g,nutriments.sugars_serving,nutriments.sugars_value,nutriments.calcium,nutriments.calcium_100g,nutriments.calcium_serving,nutriments.calcium_value,nutriments.fat_label,nutriments.nova-group,nutriments.nova-group_100g,nutriments.nova-group_serving,nutriments.chloride,nutriments.chloride_100g,nutriments.chloride_value,nutriments.magnesium,nutriments.magnesium_100g,nutriments.magnesium_value,nutriments.potassium,nutriments.potassium_100g,nutriments.potassium_value,nutriments.alcohol,nutriments.alcohol_100g,nutriments.alcohol_serving,nutriments.alcohol_value,nutriments.bicarbonate,nutriments.bicarbonate_100g,nutriments.bicarbonate_serving,nutriments.bicarbonate_value,nutriments.fluoride,nutriments.fluoride_100g,nutriments.fluoride_serving,nutriments.fluoride_value,nutriments.iron,nutriments.iron_100g,nutriments.iron_serving,nutriments.iron_value,nutriments.magnesium_serving,nutriments.ph,nutriments.ph_100g,nutriments.ph_serving,nutriments.ph_value,nutriments.potassium_serving,nutriments.alpha-linolenic-acid,nutriments.alpha-linolenic-acid_100g,nutriments.alpha-linolenic-acid_serving,nutriments.alpha-linolenic-acid_value,nutriments.arachidic-acid,nutriments.arachidic-acid_100g,nutriments.arachidic-acid_serving,nutriments.arachidic-acid_value,nutriments.arachidonic-acid,nutriments.arachidonic-acid_100g,nutriments.arachidonic-acid_serving,nutriments.arachidonic-acid_value,nutriments.behenic-acid,nutriments.behenic-acid_100g,nutriments.behenic-acid_serving,nutriments.behenic-acid_value,nutriments.biotin,nutriments.biotin_100g,nutriments.biotin_serving,nutriments.biotin_value,nutriments.butyric-acid,nutriments.butyric-acid_100g,nutriments.butyric-acid_serving,nutriments.butyric-acid_value,nutriments.carbon-footprint-from-known-ingredients_product,nutriments.chloride_serving,nutriments.nitrate,nutriments.nitrate_100g,nutriments.nitrate_serving,nutriments.nitrate_value,nutriments.silica,nutriments.silica_100g,nutriments.silica_serving,nutriments.silica_value,nutriments.sulphate,nutriments.sulphate_100g,nutriments.sulphate_serving,nutriments.sulphate_value,nutriments.vitamin-b1,nutriments.vitamin-b12,nutriments.vitamin-b12_100g,nutriments.vitamin-b12_serving,nutriments.vitamin-b12_value,nutriments.vitamin-b1_100g,nutriments.vitamin-b1_serving,nutriments.vitamin-b1_value,nutriments.vitamin-b2,nutriments.vitamin-b2_100g,nutriments.vitamin-b2_serving,nutriments.vitamin-b2_value,nutriments.vitamin-b9,nutriments.vitamin-b9_100g,nutriments.vitamin-b9_serving,nutriments.vitamin-b9_value,nutriments.vitamin-pp,nutriments.vitamin-pp_100g,nutriments.vitamin-pp_serving,nutriments.vitamin-pp_value,nutriments.carbon-footprint-from-known-ingredients_100g,nutriments.carbon-footprint-from-known-ingredients_serving,nutriments.choline,nutriments.choline_100g,nutriments.choline_serving,nutriments.choline_value,nutriments.cocoa,nutriments.cocoa_100g,nutriments.cocoa_serving,nutriments.cocoa_value,nutriments.starch,nutriments.starch_100g,nutriments.starch_serving,nutriments.starch_value,nutriments.fruits-vegetables-nuts-estimate,nutriments.fruits-vegetables-nuts-estimate_100g,nutriments.fruits-vegetables-nuts-estimate_serving,nutriments.fruits-vegetables-nuts-estimate_value,nutriments.fruits-vegetables-nuts,nutriments.fruits-vegetables-nuts_100g,nutriments.fruits-vegetables-nuts_serving,nutriments.fruits-vegetables-nuts_value,nutriments.vitamin-b6,nutriments.vitamin-b6_100g,nutriments.vitamin-b6_serving,nutriments.vitamin-b6_value,nutriments.vitamin-e,nutriments.vitamin-e_100g,nutriments.vitamin-e_serving,nutriments.vitamin-e_value,nutriments.phosphorus,nutriments.phosphorus_100g,nutriments.phosphorus_value,nutriments.monounsaturated-fat,nutriments.monounsaturated-fat_100g,nutriments.monounsaturated-fat_serving,nutriments.monounsaturated-fat_value,nutriments.oleic-acid,nutriments.oleic-acid_100g,nutriments.oleic-acid_serving,nutriments.oleic-acid_value,nutriments.polyunsaturated-fat,nutriments.polyunsaturated-fat_100g,nutriments.polyunsaturated-fat_serving,nutriments.polyunsaturated-fat_value,nutriments.vitamin-d,nutriments.vitamin-d_100g,nutriments.vitamin-d_serving,nutriments.vitamin-d_value,nutriments.added-sugars,nutriments.added-sugars_100g,nutriments.added-sugars_serving,nutriments.added-sugars_value,nutriments.caffeine,nutriments.caffeine_100g,nutriments.caffeine_serving,nutriments.caffeine_value,nutriments.copper,nutriments.copper_100g,nutriments.copper_serving,nutriments.copper_value,nutriments.manganese,nutriments.manganese_100g,nutriments.manganese_serving,nutriments.manganese_value,nutriments.phosphorus_serving,nutriments.selenium,nutriments.selenium_100g,nutriments.selenium_serving,nutriments.selenium_value,nutriments.vitamin-a,nutriments.vitamin-a_100g,nutriments.vitamin-a_serving,nutriments.vitamin-a_value,nutriments.vitamin-c,nutriments.vitamin-c_100g,nutriments.vitamin-c_serving,nutriments.vitamin-c_value,nutriments.vitamin-k,nutriments.vitamin-k_100g,nutriments.vitamin-k_serving,nutriments.vitamin-k_value,nutriments.zinc,nutriments.zinc_100g,nutriments.zinc_serving,nutriments.zinc_value,nutriments.iodine,nutriments.iodine_100g,nutriments.iodine_value,nutriments.pantothenic-acid,nutriments.pantothenic-acid_100g,nutriments.pantothenic-acid_serving,nutriments.pantothenic-acid_value,nutriments.cholesterol,nutriments.cholesterol_100g,nutriments.cholesterol_serving,nutriments.cholesterol_value,nutriments.fr-residu-sec-a-105-c,nutriments.fr-residu-sec-a-105-c_100g,nutriments.fr-residu-sec-a-105-c_serving,nutriments.fr-residu-sec-a-105-c_value,nutriments.trans-fat,nutriments.trans-fat_100g,nutriments.trans-fat_serving,nutriments.trans-fat_value,nutriments.nutrition-score_value,nutriments.iodine_serving,nutriments.omega-3-fat,nutriments.omega-3-fat_100g,nutriments.omega-3-fat_value,nutriments.omega-6-fat,nutriments.omega-6-fat_100g,nutriments.omega-6-fat_value,nutriments.omega-9-fat,nutriments.omega-9-fat_100g,nutriments.omega-9-fat_value,nutriments.omega-6-fat_serving,nutriments.lactose,nutriments.lactose_100g,nutriments.lactose_serving,nutriments.lactose_value,nutriments.carbohydrates_prepared,nutriments.carbohydrates_prepared_100g,nutriments.carbohydrates_prepared_serving,nutriments.carbohydrates_prepared_value,nutriments.energy-kcal_prepared,nutriments.energy-kcal_prepared_100g,nutriments.energy-kcal_prepared_serving,nutriments.energy-kcal_prepared_value,nutriments.energy-kj_prepared,nutriments.energy-kj_prepared_100g,nutriments.energy-kj_prepared_serving,nutriments.energy-kj_prepared_value,nutriments.energy_prepared,nutriments.energy_prepared_100g,nutriments.energy_prepared_serving,nutriments.energy_prepared_value,nutriments.fat_prepared,nutriments.fat_prepared_100g,nutriments.fat_prepared_serving,nutriments.fat_prepared_value,nutriments.fiber_prepared,nutriments.fiber_prepared_100g,nutriments.fiber_prepared_serving,nutriments.fiber_prepared_value,nutriments.proteins_prepared,nutriments.proteins_prepared_100g,nutriments.proteins_prepared_serving,nutriments.proteins_prepared_value,nutriments.salt_prepared,nutriments.salt_prepared_100g,nutriments.salt_prepared_serving,nutriments.salt_prepared_value,nutriments.saturated-fat_prepared,nutriments.saturated-fat_prepared_100g,nutriments.saturated-fat_prepared_serving,nutriments.saturated-fat_prepared_value,nutriments.sodium_prepared,nutriments.sodium_prepared_100g,nutriments.sodium_prepared_serving,nutriments.sodium_prepared_value,nutriments.sugars_prepared,nutriments.sugars_prepared_100g,nutriments.sugars_prepared_serving,nutriments.sugars_prepared_value,nutriments.fr-strontium_prepared,nutriments.fr-strontium_prepared_serving,nutriments.fr-strontium_prepared_value,nutriments.fr-sulfate_prepared,nutriments.fr-sulfate_prepared_serving,nutriments.fr-sulfate_prepared_value,nutriments.linoleic-acid,nutriments.linoleic-acid_100g,nutriments.linoleic-acid_value,nutriments.maltodextrins,nutriments.maltodextrins_100g,nutriments.maltodextrins_value,nutriments.omega-3-fat_serving,nutriments.magnesium_prepared,nutriments.magnesium_prepared_100g,nutriments.magnesium_prepared_serving,nutriments.magnesium_prepared_value,nutriments.fructose,nutriments.fructose_100g,nutriments.fructose_serving,nutriments.fructose_value,nutriments.calcium_prepared,nutriments.calcium_prepared_100g,nutriments.calcium_prepared_value,nutriments.vitamin-c_prepared,nutriments.vitamin-c_prepared_100g,nutriments.vitamin-c_prepared_value,nutriments.vitamin-d_prepared,nutriments.vitamin-d_prepared_100g,nutriments.vitamin-d_prepared_value,nutriments.acides-gras-mono-insatures_100g,nutriments.acides-gras-mono-insatures_serving,nutriments.acides-gras-polyinsatures_100g,nutriments.acides-gras-polyinsatures_serving,nutriments.polyols,nutriments.polyols_100g,nutriments.polyols_serving,nutriments.polyols_value,nutriments.carbon-footprint,nutriments.carbon-footprint_100g,nutriments.carbon-footprint_serving,nutriments.carbon-footprint_value,nutriments.beta-glucan,nutriments.beta-glucan_100g,nutriments.beta-glucan_serving,nutriments.beta-glucan_value,nutriments.calcium_prepared_serving,nutriments.iron_prepared,nutriments.iron_prepared_100g,nutriments.iron_prepared_serving,nutriments.iron_prepared_value,nutriments.phosphorus_prepared,nutriments.phosphorus_prepared_100g,nutriments.phosphorus_prepared_serving,nutriments.phosphorus_prepared_value,nutriments.potassium_prepared,nutriments.potassium_prepared_100g,nutriments.potassium_prepared_serving,nutriments.potassium_prepared_value,nutriments.vitamin-b1_prepared,nutriments.vitamin-b1_prepared_100g,nutriments.vitamin-b1_prepared_serving,nutriments.vitamin-b1_prepared_value,nutriments.vitamin-c_prepared_serving,nutriments.vitamin-d_prepared_serving,nutriments.zinc_prepared,nutriments.zinc_prepared_100g,nutriments.zinc_prepared_serving,nutriments.zinc_prepared_value,nutriments.fruits-vegetables-nuts-dried,nutriments.fruits-vegetables-nuts-dried_100g,nutriments.fruits-vegetables-nuts-dried_serving,nutriments.fruits-vegetables-nuts-dried_value,nutriments.extrait-sec-a-180-c_prepared,nutriments.extrait-sec-a-180-c_prepared_100g,nutriments.extrait-sec-a-180-c_prepared_serving,nutriments.extrait-sec-a-180-c_prepared_value,nutriments.fr-nitrates_prepared,nutriments.fr-nitrates_prepared_100g,nutriments.fr-nitrates_prepared_serving,nutriments.fr-nitrates_prepared_value,nutriments.fr-sulfates_prepared,nutriments.fr-sulfates_prepared_100g,nutriments.fr-sulfates_prepared_serving,nutriments.fr-sulfates_prepared_value,nutriments.nitrates_prepared,nutriments.nitrates_prepared_100g,nutriments.nitrates_prepared_serving,nutriments.nitrates_prepared_value,nutriments.sulfates_prepared,nutriments.sulfates_prepared_100g,nutriments.sulfates_prepared_serving,nutriments.sulfates_prepared_value,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_100g,nutriments.attention-boisson-preparee-200-ml-deux-cuillieres-de-13-5g-la-valeur-indiquee-sur-l-emballage-pour-100-ml-et-non-100g-correspond-donc-aux-valeurs-pour-une-cuilliere-bombee-soit-13-5g_prepared_serving,nutriments.0,nutriments.0_100g,nutriments.0_label,nutriments.0_serving,nutriments.0_value,nutriments.dry-residue,nutriments.dry-residue_100g,nutriments.dry-residue_serving,nutriments.dry-residue_value,nutriments.omega-9-fat_serving,nutriments.en-0,nutriments.en-0_100g,nutriments.en-0_label,nutriments.en-0_value,nutriments.beta-carotene,nutriments.beta-carotene_100g,nutriments.beta-carotene_value,nutriments.maltodextrins_serving,nutriments.carbon-footprint-from-meat-or-fish_100g,nutriments.carbon-footprint-from-meat-or-fish_product,nutriments.carbon-footprint-from-meat-or-fish_serving,nutriments.en-fibres-du-son-de-ble,nutriments.en-fibres-du-son-de-ble_100g,nutriments.en-fibres-du-son-de-ble_serving,nutriments.en-fibres-du-son-de-ble_value,nutriments.gamma-linolenic-acid,nutriments.gamma-linolenic-acid_100g,nutriments.gamma-linolenic-acid_serving,nutriments.gamma-linolenic-acid_value,nutriments.energy-g,nutriments.energy-g_100g,nutriments.energy-g_serving,nutriments.energy-g_value,nutriments.phosphore_100g,nutriments.phosphore_serving,nutriments.serum-proteins,nutriments.serum-proteins_100g,nutriments.serum-proteins_serving,nutriments.serum-proteins_value,nutriments.vitamine-b1_100g,nutriments.vitamine-b1_serving,nutriments.molybdenum,nutriments.molybdenum_100g,nutriments.molybdenum_serving,nutriments.molybdenum_value,nutriments.cocoa_prepared,nutriments.cocoa_prepared_100g,nutriments.cocoa_prepared_serving,nutriments.cocoa_prepared_value,nutriments.glucides assimilables,nutriments.glucides assimilables_100g,nutriments.glucides assimilables_serving,nutriments.glucides assimilables_value,nutriments.fr-extrait-sec-a-180-c,nutriments.fr-extrait-sec-a-180-c_100g,nutriments.fr-extrait-sec-a-180-c_serving,nutriments.fr-extrait-sec-a-180-c_value,nutriments.fr-nitrates,nutriments.fr-nitrates_100g,nutriments.fr-nitrates_serving,nutriments.fr-nitrates_value,nutriments.fr-sulfates,nutriments.fr-sulfates_100g,nutriments.fr-sulfates_serving,nutriments.fr-sulfates_value,nutriments.caffeine_prepared,nutriments.caffeine_prepared_serving,nutriments.caffeine_prepared_value,nutriments.fr-residu-a-sec,nutriments.fr-residu-a-sec_100g,nutriments.fr-residu-a-sec_serving,nutriments.fr-residu-a-sec_value,nutriments.fr-0,nutriments.fr-0_100g,nutriments.fr-0_label,nutriments.fr-0_serving,nutriments.fr-0_value,nutriments.vitamine-d_100g,nutriments.vitamine-d_serving,nutriments.fr-strontium,nutriments.fr-strontium_100g,nutriments.fr-strontium_serving,nutriments.fr-strontium_value,nutriments.acide-pantothenique-vitamine-b5_100g,nutriments.acide-pantothenique-vitamine-b5_serving,nutriments.vitamine-b3-pp-niacine_100g,nutriments.vitamine-b3-pp-niacine_serving,nutriments.vitamine-c-acide-ascorbique_100g,nutriments.vitamine-c-acide-ascorbique_serving,nutriments.vitamine-e-tocopherol_100g,nutriments.vitamine-e-tocopherol_serving,nutriments.fer_100g,nutriments.fer_serving,nutriments.fr-residu-sec,nutriments.fr-residu-sec_100g,nutriments.fr-residu-sec_serving,nutriments.fr-residu-sec_value,nutriments.fr-residu-sec-a-180-c,nutriments.fr-residu-sec-a-180-c_100g,nutriments.fr-residu-sec-a-180-c_serving,nutriments.fr-residu-sec-a-180-c_value,nutriments.nitrite,nutriments.nitrite_100g,nutriments.nitrite_serving,nutriments.nitrite_value,nutriments.biotin_prepared,nutriments.biotin_prepared_serving,nutriments.biotin_prepared_value,nutriments.pantothenic-acid_prepared,nutriments.pantothenic-acid_prepared_serving,nutriments.pantothenic-acid_prepared_value,nutriments.vitamin-b12_prepared,nutriments.vitamin-b12_prepared_serving,nutriments.vitamin-b12_prepared_value,nutriments.vitamin-b2_prepared,nutriments.vitamin-b2_prepared_serving,nutriments.vitamin-b2_prepared_value,nutriments.vitamin-b6_prepared,nutriments.vitamin-b6_prepared_serving,nutriments.vitamin-b6_prepared_value,nutriments.vitamin-b9_prepared,nutriments.vitamin-b9_prepared_serving,nutriments.vitamin-b9_prepared_value,nutriments.vitamin-e_prepared,nutriments.vitamin-e_prepared_serving,nutriments.vitamin-e_prepared_value,nutriments.vitamin-pp_prepared,nutriments.vitamin-pp_prepared_serving,nutriments.vitamin-pp_prepared_value,nutriments.fr-nitrate,nutriments.fr-nitrate_100g,nutriments.fr-nitrate_serving,nutriments.fr-nitrate_value,nutriments.chromium,nutriments.chromium_100g,nutriments.chromium_serving,nutriments.chromium_value,nutriments.vitamine-pp_100g,nutriments.vitamine-pp_serving,nutriments.vit-pp_100g,nutriments.vit-pp_serving,nutriments.vitamin-b2_prepared_100g,nutriments.vitamin-b6_prepared_100g,nutriments.cerotic-acid,nutriments.cerotic-acid_100g,nutriments.cerotic-acid_serving,nutriments.cerotic-acid_value,nutriments.fr-sulfate,nutriments.fr-sulfate_100g,nutriments.fr-sulfate_serving,nutriments.fr-sulfate_value,nutriments.fr-riboflavine-b2,nutriments.fr-riboflavine-b2_100g,nutriments.fr-riboflavine-b2_serving,nutriments.fr-riboflavine-b2_value,nutriments.elaidic-acid,nutriments.elaidic-acid_100g,nutriments.elaidic-acid_serving,nutriments.elaidic-acid_value,nutriments.pl-0,nutriments.pl-0_100g,nutriments.pl-0_label,nutriments.pl-0_serving,nutriments.pl-0_value,nutriments.taurine,nutriments.taurine_100g,nutriments.taurine_serving,nutriments.taurine_value,nutriments.fr-بقايا-جافة,nutriments.fr-بقايا-جافة_100g,nutriments.fr-بقايا-جافة_serving,nutriments.fr-بقايا-جافة_value,nutriments.fr-بوتاسيوم,nutriments.fr-بوتاسيوم_100g,nutriments.fr-بوتاسيوم_serving,nutriments.fr-بوتاسيوم_value,nutriments.fr-بيكربونات,nutriments.fr-بيكربونات_100g,nutriments.fr-بيكربونات_serving,nutriments.fr-بيكربونات_value,nutriments.fr-سولفات,nutriments.fr-سولفات_100g,nutriments.fr-سولفات_serving,nutriments.fr-سولفات_value,nutriments.fr-كلسيوم,nutriments.fr-كلسيوم_100g,nutriments.fr-كلسيوم_serving,nutriments.fr-كلسيوم_value,nutriments.fr-كلورور,nutriments.fr-كلورور_100g,nutriments.fr-كلورور_serving,nutriments.fr-كلورور_value,nutriments.fr-مانزيوم,nutriments.fr-مانزيوم_100g,nutriments.fr-مانزيوم_serving,nutriments.fr-مانزيوم_value,nutriments.fr-نيترات,nutriments.fr-نيترات_100g,nutriments.fr-نيترات_serving,nutriments.fr-نيترات_value,nutriments.lignoceric-acid,nutriments.lignoceric-acid_100g,nutriments.lignoceric-acid_serving,nutriments.lignoceric-acid_value,nutriments.maltose,nutriments.maltose_100g,nutriments.maltose_serving,nutriments.maltose_value,nutriments.vit-5_100g,nutriments.vit-5_serving,nutriments.vit-b3_100g,nutriments.vit-b3_serving,nutriments.vit-b6_100g,nutriments.vit-b6_serving,nutriments.vit-e_100g,nutriments.vit-e_serving,nutriments.vit-h_100g,nutriments.vit-h_serving,nutriments.phylloquinone,nutriments.phylloquinone_100g,nutriments.phylloquinone_serving,nutriments.phylloquinone_value,nutriments.proteins_label,nutriments.nutrition-score-fr_value,nutriments.es-vitamina-e,nutriments.es-vitamina-e_100g,nutriments.es-vitamina-e_value,nutriments.alcohol_prepared,nutriments.alcohol_prepared_100g,nutriments.alcohol_prepared_serving,nutriments.alcohol_prepared_value,nutriments.poisson,nutriments.poisson_100g,nutriments.poisson_serving,nutriments.poisson_value,nutriments.de-mate,nutriments.de-mate_100g,nutriments.de-mate_value,nutriments.fr-nitrite,nutriments.fr-nitrite_100g,nutriments.fr-nitrite_serving,nutriments.fr-nitrite_value,nutriments.es-betaglucanos,nutriments.es-betaglucanos_100g,nutriments.es-betaglucano

In [9]:
## Identify Missing Values

## The number of missing values in each column is calculated and sorted in descending order.

## This helps identify which columns contain the highest number of missing values and require further attention during the data-cleaning process.

df.isnull().sum().sort_values(ascending=False)

nutriments.fruits-vegetables-nuts-estimate_prepared_unit    12050
nutriments.fr-fibres-alimentaired_value                     12049
nutriments.beta-glucane-d-avoine_value                      12049
nutriments.beta-glucane-d-avoine_unit                       12049
nutriments.beta-glucane-d-avoine_serving                    12049
                                                            ...
nutriments.energy_value                                       728
nutriments.energy_unit                                        728
brands                                                        669
product_name                                                  573
code                                                            0
Length: 1405, dtype: int64

In [10]:
## Calculate Missing Value Percentage

## The percentage of missing values in each column is calculated based on the total number of records in the dataset.

## Examining the missing values as percentages provides a clearer understanding of the extent of missing data across different columns.


(df.isnull().sum() / len(df)) * 100

brands                                        5.551867
code                                          0.000000
product_name                                  4.755187
nutriments.carbohydrates                      6.464730
nutriments.carbohydrates_100g                 7.004149
                                               ...
nutriments.beta-glucane-d-avoine_label       99.991701
nutriments.beta-glucane-d-avoine_modifier    99.991701
nutriments.beta-glucane-d-avoine_serving     99.991701
nutriments.beta-glucane-d-avoine_unit        99.991701
nutriments.beta-glucane-d-avoine_value       99.991701
Length: 1405, dtype: float64

**Check Missing Values in Product Name**

Since `product_name` is an important field for product-level analysis, we first check whether it contains any missing values.

In [11]:
df['product_name'].isnull().sum()

np.int64(573)

**Check Missing Values in Brands**

The `brands` column is also important for brand-level analysis. We check this column separately to identify the number of missing values.

In [12]:
df['brands'].isnull().sum()

np.int64(669)

**Identify Records with Missing Product Name and Brand**

Rows where both `product_name` and `brands` are missing do not contain either of the two key identification fields.

These records are checked separately so they can be removed before handling individual missing values.

In [13]:
df[['product_name', 'brands']].isnull().all(axis=1).sum()

np.int64(267)

**Remove Records with Missing Product Name and Brand**

Records where both `product_name` and `brands` are missing are removed because neither product nor brand information is available for those records.

Rows where only one of the two fields is missing are retained because the available product or brand information can still be useful for analysis.

In [14]:
df.dropna(subset=['product_name', 'brands'], how='all', inplace=True)

**Fill Remaining Missing Values**

After removing records where both fields were missing, the remaining missing values in `product_name` and `brands` are filled with `"Missing"`.

This preserves records where one field is available while clearly indicating that the other information was not provided in the original data.

In [15]:
df[['product_name', 'brands']] = df[['product_name', 'brands']].fillna('Missing')

**Verify Product Name and Brand Cleaning**

The `product_name` and `brands` columns are displayed after cleaning to verify that the missing values have been handled correctly.

In [16]:
df[['product_name', 'brands']].head(20)

              product_name                                brands
0                 Sidi Ali                              Sidi Ali
1                    Perly                                Jaouda
2                 Sidi Ali                              sidi ali
3   Eau minérale naturelle  Les Eaux Minérales d'oulmès,Sidi Ali
4                 اكوافينا                              AQUAFINA
5                     Lait                                Jaouda
6            Eau De Source                            Cristaline
7     Fromage blanc nature               MILKY FOOD PROFESSIONAL
8            uht jaouda 1L                                Jaouda
9                     Jben                                Jaouda
10               Ain Saïss                                Danone
11   Eau minéral naturelle                             Ain atlas
12           6111035000027                              Sidi Ali
13   Marmite Yeast Extract                      Marmite,Unilever
14                 Missing                                Jaouda
15              Lait Frais                       centrale danone
16                 Missing                                 lilia
17          Original Taste                             Coca-Cola
18                اكوافينا                                 pepsi
19    Prince Goût Chocolat                                    Lu

In [17]:
## Store the Cleaned DataFrame

## The cleaned DataFrame is stored using the IPython `%store` command so that the processed dataset can be accessed in another Jupyter Notebook without having to repeat the previous data-loading and cleaning steps.

%store df

Stored 'df' (DataFrame)